## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html#ansible-collections-community-vmware-vmware-vswitch-module 
## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_portgroup_module.html 

---
- name: deploy DC VM
  hosts: localhost
  become: false   #disable become privilege we don't need privilege for this script and 
  gather_facts: false   #never system information so let's disable also fax gathering
  collections:
    - community.vmware     #define the namespace of a collection under community.vmware #we could shorten the name in this playbook
  pre_tasks:   #pre-task is quite useful, let me include one variable file in my case vars.yml
    - include_vars: vars.yml
  vars:
    ansible_python_interpreter: /bin/python3

  tasks: 
    - name: Create Lab Standard Switch
      community.vmware.vmware_vswitch:
          hostname: '{{ esxi_hostname }}'
          username: '{{ esxi_username }}'
          password: '{{ esxi_password }}'
          validate_certs: no
          switch: '{{ canonical }}'
      delegate_to: localhost


    - name: Waiting 10 seconds for completing switch
      wait_for:
        timeout: 10
      delegate_to: localhost


    - name: Adding Trunk Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ canonical }}"
          portgroup: "{{ canonical + '-Trunk' }}"
          vlan_id: 4095
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Management Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ canonical}}"
          portgroup: "{{ canonical + '-Mgmt' }}"
          vlan_id: 101
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A Storage Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ canonical }}"
          portgroup: "{{ canonical + '-Storage' }}"
          vlan_id: 102
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Adding Site A vMotion Portgroup
      community.vmware.vmware_portgroup:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          esxi_hostname: "{{ esxi_hostname }}"
          validate_certs: no
          switch: "{{ canonical }}"
          portgroup: "{{ canonical + '-vMotion' }}"
          vlan_id: 103
          security:
              promiscuous_mode: True
              mac_changes: True
              forged_transmits: True
      delegate_to: localhost

    - name: Deploy VyOS ova
      community.vmware.vmware_deploy_ovf:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + canonical }}"
          esxi_hostname: '{{ esxi_hostname }}'
          datastore: '{{ datastore_name }}'
          name: "{{ canonical + '-Router' }}"
          networks:  { "{{ public_net }}": "{{ public_net }}", "{{ private_net }}": "{{ private_net }}" }
          power_on: no
          ovf: /mnt/c/vyos.ovf   
      delegate_to: localhost


    - name: Perform vMotion of virtual machine
      community.vmware.vmware_vmotion:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_name: "{{ canonical + '-Router' }}"
          destination_host: '{{ esxi_hostname }}'
      delegate_to: localhost


    - name: Set the state of a virtual machine to poweron
      community.vmware.vmware_guest_powerstate:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: 'false'
          folder: '{{ full_folder_prefix + canonical }}'
          name: "{{ canonical + '-Router' }}"
          state: powered-on
      delegate_to: localhost


    - name: Waiting 60 seconds for completing bootup
      wait_for:
        timeout: 60
      delegate_to: localhost


    - name: VyOS Router Configuration
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          datacenter: '{{ datacenter_name }}'
          folder: "{{ full_folder_prefix + canonical }}"
          vm_id: "{{ canonical + '-Router' }}"
          vm_id_type: vm_name
          vm_username: 'vyos'
          vm_password: 'vyos'
          vm_shell: /bin/vbash
          vm_shell_cwd: "/tmp"
          vm_shell_args: |-
            -c "source /opt/vyatta/etc/functions/script-template
            configure
            set system login user admin full-name Admin_User
            set system login user admin authentication plaintext-password VMware1!
            set service ssh port 22
            
            set interfaces ethernet eth0 address 172.16.11.63/24
            set interfaces ethernet eth0 description Outside
            set protocols static route 0.0.0.0/0 next-hop 172.16.11.1
            
            set system name-server 172.16.11.20
            set system ntp server kr.pool.ntp.org
            
            set interfaces ethernet eth1 vif 101 description 'VLAN 101 - Site A Management'
            set interfaces ethernet eth1 vif 101 address 10.10.1.1/24
            set interfaces ethernet eth1 vif 102 description 'VLAN 102 - Site A Storage'
            set interfaces ethernet eth1 vif 102 address 10.10.2.1/24
            
            set nat source rule 100 outbound-interface eth0
            set nat source rule 100 source address 10.10.1.0/24
            set nat source rule 100 translation address masquerade
            
            commit
            save"
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout

    - name: Deploy Domain Controller VM from Template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ canonical + '-DC' }}"
        state: "poweredon"
        datacenter: '{{ datacenter_name }}'
        folder: "{{ full_folder_prefix + canonical }}"
        esxi_hostname: '{{ esxi_hostname }}'
        datastore: "{{ datastore_name }}"
        template: "{{ template_name }}"
        disk:
        - size_gb: 200
          type: "thin"
          controller_type: "lsilogicsas"
          controller_number: 0
          unit_number: 2
  #     linked_clone: True
  #     snapshot_src: "{{ snapshot_src_name }}"
        networks:
        - name: "{{ canonical + '-Mgmt' }}"
          label: "Network adapter 1"
          connected: True
          start_connected: True
          ip: 10.10.1.2
          netmask: 255.255.255.0
          gateway: 10.10.1.1
          dns_servers: 
          - 127.0.0.1
          - 172.16.11.20
          type: static
        customization:
          password: VMware1!
          autologon: true
          autologoncount: 1
        wait_for_customization: yes
        wait_for_customization_timeout: 360
      delegate_to: localhost
      ignore_errors: yes     

    - name: Perform vMotion of virtual machine
      community.vmware.vmware_vmotion:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_name: "{{ canonical + '-DC' }}"
          destination_host: '{{ esxi_hostname }}'
      delegate_to: localhost

    - name: Connect Network
      community.vmware.vmware_guest_network:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        validate_certs: no
        name: "{{ canonical + '-DC' }}"
        label: "Network adapter 1"
        state: present
        network_name: "{{ canonical + '-Mgmt' }}"
        connected: true
        start_connected: true
      delegate_to: localhost

    - name: shutdown VM to change network connection
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ canonical + '-DC' }}"
        state: "shutdownguest"
        state_change_timeout: 60
      delegate_to: localhost

    - name: Poweron DC VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ canonical + '-DC' }}"
        state: "poweredon"
        state_change_timeout: 60        
      delegate_to: localhost

    - name: Waiting 60 seconds for completing bootup
      wait_for:
        timeout: 60
      delegate_to: localhost

    - name: Install_WindowsFeatures_AD-DS
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ canonical + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout

    - name: Import_Module_ADDSDeployment
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ canonical + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "Import-Module ADDSDeployment"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout


    - name: Install_First_ADDSForest
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ canonical + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "(Install-ADDSForest -CreateDnsDelegation:$false -DatabasePath C:\Windows\NTDS -DomainMode WinThreshold -DomainName wish.kh -DomainNetbiosName WISH -ForestMode WinThreshold -InstallDns:$true -LogPath C:\Windows\NTDS -NoRebootOnCompletion:$false -SysvolPath C:\Windows\SYSVOL -Force:$true -SafeModeAdministratorPassword (ConvertTo-SecureString -AsPlainText "VMware1!" -force)")"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout
      ignore_errors: yes      

    - name: Waiting 60 seconds for completing bootup
      wait_for:
        timeout: 120
      delegate_to: localhost

    - name: Deploy Domain Controller VM from Template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ canonical + '-DC' }}"
        networks:
        - name: "{{ canonical + '-Mgmt' }}"
          label: "Network adapter 1"
          connected: True
          start_connected: True
          ip: 10.10.1.2
          netmask: 255.255.255.0
          gateway: 10.10.1.1
          dns_servers: 
          - 127.0.0.1
          - 172.16.11.20
