---
- name: deploy DC VM
  hosts: localhost
  become: false   #disable become privilege we don't need privilege for this script and 
  gather_facts: false   #never system information so let's disable also fax gathering
  collections:
    - community.vmware     #define the namespace of a collection under community.vmware #we could shorten the name in this playbook
  pre_tasks:   #pre-task is quite useful, let me include one variable file in my case vars.yml
    - include_vars: vars.yml
  vars:
    ansible_python_interpreter: /bin/python3
    
  tasks:
    - name: Install_First_ADDSForest
      community.vmware.vmware_vm_shell:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: 'false'
          vm_id: "{{ canonical + '-DC' }}"
          vm_id_type: vm_name
          vm_username: 'Administrator'
          vm_password: 'VMware1!'
          vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
          vm_shell_args: '-command "(Install-ADDSForest -CreateDnsDelegation:$false -DatabasePath C:\Windows\NTDS -DomainMode WinThreshold -DomainName wish.kh -DomainNetbiosName WISH -ForestMode WinThreshold -InstallDns:$true -LogPath C:\Windows\NTDS -NoRebootOnCompletion:$false -SysvolPath C:\Windows\SYSVOL -Force:$true -SafeModeAdministratorPassword (ConvertTo-SecureString -AsPlainText "VMware1!" -force)")"'
          vm_shell_cwd: 'c:\Users\Administrator'
          wait_for_process: True
          timeout: 180
      delegate_to: localhost
      register: shell_command_with_wait_timeout    
